clickhouse_version: "24.8.4.13"
clickhouse_cluster_name: "my"

clickhouse_shards:
  - shard: 01
    replicas:
      - name: clickhouse01
        replica: 01
      - name: clickhouse02
        replica: 02

  - shard: 02
    replicas:
      - name: clickhouse03
        replica: 01
      - name: clickhouse04
        replica: 02